name: Post-release jobs

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍distributions 📦 to PyPI
    environment: secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Setup Poetry
      run: >-
        poetry config virtualenvs.create false &&
        find flask_ninja -type d | xargs -I {} touch {}/py.typed &&
        poetry build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
